### ISSUE TITLE
Remove unneeded sandboxing code

### ISSUE THREAD

**Issue by Paul-Guerra** [markfguerra/node-socketio-chat#7]
The self executing function pattern used in chatapi.js is great but not needed when you are writing modules because of the way they are built.

- [ ] Rewrite this file in a more succinct format now that you no longer need to worry about global scope.

- [ ] Open bundle.js and look for "chatApi" to see how webpack (and all commonJS bundlers for the browsers wrap your modules in functions

**Comment by markfguerra** [comment]
Ah, I see. I took a look at the bundle.js being generated by WebPack. It looks like it does the following:

- Defines a bootstrapping function, which accepts an array of modules as a parameter. It provides an implementation of `require()` (which it has renamed to `__webpack_require__`) and then calls`'require()` on the first module.
- It immediately calls the bootstrapping function. The array of modules passed in to the bootstrap function are concatenations of our JS files (with the modified require() function) as well as our dependencies.
- You can see chatApi in there, as well as gui.js, jquery, bootstrap, style-loader and css-loader.
- All told, it includes 60 modules in this call for a total of 500k of javascript in the bundle.js file. 
- We can cut down on our JS footprint by minifying/compression, and perhaps by keeping dependencies to a minimum.

Let's zoom in on the module we're talking about, the one generated by chatapi.js

```
/***/ },
/* 2 */
/***/ function(module, exports, __webpack_require__) {

	var io = __webpack_require__(3);

	var chatApi = (function() {
		// Private members

		// The socket that communicates with the server
		var socket = io();

		// Set up functions

		// The event that fires when a message is received from the server
		socket.on('chat message', function(messageText) {
			// default listener
			console.log("Chat received from server: " + messageText);
		});

		// Return value is the public API
		return {
			sendText : function(messageText) {
				// Send message to the server.
				// Sends an event called 'chat message' containing the messageText

				// Instead of messageText, we could opt to send objects.
				socket.emit('chat message', messageText);
			},
			// Sets the listener for receiving a chat message from the server
			onMessageReceived : function(f) {
				if (typeof(f) === "function")
					socket.on('chat message', f);
				else
					console.log("Tried to call chatApi.onMessageReceived() without a function.");
			}
		};
	})();

	module.exports = chatApi;

/***/ },
```

By virtue of what it's generating (functions), it keeps your variables off the global namespace by default. Every var is function scoped, and the only thing that makes its way to the outside is module.exports.

Pretty cool. I guess that makes my self executing function unnecessary.

**Comment by Paul-Guerra** [comment]
💯 👍
